### ISSUE TITLE
Legacy La Palma read/write functions

### ISSUE THREAD

**Issue by grviss** [ISP-SST/ISPy#1]
Include equivalents of IDL's:

- [ ] lp_header
- [ ] make_lp_header
- [ ] lp_read (get full cube in memory)
- [ ] lp_get (get slice in memory)
- [ ] lp_write (write full cube to disc)
- [ ] lp_put (write slice to disc)

Perhaps lp_read/lp_get could be one function, with option to specify which slice to read. Similarly, lp_write/lp_put could be one function, with option specifying which slice to write.

**Comment by AlexPietrow** [comment]
I can take this, got python 2 code doing it
