### ISSUE TITLE
SOLARNET FITS read functions

### ISSUE THREAD

**Issue by grviss** [ISP-SST/ISPy#2]
- [x] get time from tabulated coordinates
- [x] get wavelength from tabulated coordinates
- [x] get XY coordinate from tabulated coordinates

**Comment by AlexPietrow** [comment]
I think that this can basically be done with astropy.io.fits.

**Comment by grviss** [comment]
True, but getting the tabulated coordinates is a bit more involved, so it would be good to have wrappers for that. Modified the checklist.
