### ISSUE TITLE
File search

### ISSUE THREAD

**Issue by grviss** [ISP-SST/ISPy#4]
Add file listing function(s), similar to `fcube` in IDL or `iris_files()` in SolarSoft, e.g.:
```
f = find.fits()
Searched: ./
0 nb_3950_2016-09-19T09:28:36_scan=69_corrected.fits
1 nb_3950_2016-09-19T09:28:36_scan=70_corrected.fits

hdr = fits.getheader(f[0])
```

**Comment by cdiazbas** [comment]
We can use an external and common library for that:

import glob
lista = glob.glob('/home/*.zip')

But we can also rename this function to include this functionality in the library.

**Comment by grviss** [comment]
Makes more sense to use that then, even though a wrapper could be nice for common file searches (*.nc, *.fits, *cube, *idlsave, etc.).
