### ISSUE TITLE
 Files not downloading through pip

### ISSUE THREAD

**Issue by AlexPietrow** [ISP-SST/ISPy#53]
I just tried using the plotline function from ISPy.util.lineplot and when using it told me that it could not find 
crisp::__init__: ERROR, reflectivities file not found in /home/alpi/.local/lib/python3.5/site-packages/ISPy/spec/crisp_ref.txt

This means that pip install git+[gitlink] does not bring in the txt file for some reason. Is this something that we can solve? Otherwise, we should probably not suggest using pip.

**Comment by calvofl0** [comment]
The name of all data files to be installed need to be explicitly listed inside a file called `package_data`, at the root of each module.
