### ISSUE TITLE
Setup doesn't work for python >=3.12 

### ISSUE THREAD

**Issue by demichieldewilde** [ISP-SST/ISPy#60]
The module numpy.distutils has been deprecated in NumPy 1.23.0. It will be removed for Python 3.12; for Python <= 3.11 it will not be removed until 2 years after the Python 3.12 release (Oct 2025).

Therefore the setup does not longer work as it relies on this module.

**Comment by cdiazbas** [comment]
Commit 6cf06b5242be0ca0dfbe1d4e0c3b280a13deeb47 addresses and resolves issue #13
